language: elixir
elixir:
  - 1.6.6
  - 1.7.3
  - 1.8.1
otp_release:
  - 21.1
sudo: false
matrix:
  include:
    - install:
      - mix local.hex --force
      - mix local.rebar --force
      - mix archive.install hex credo '~> 0.10' --force
      - mix deps.get
      script:
      - MIX_ENV=test mix espec --trace
